# coding: utf-8

"""
    ocoutest

    simple test  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.rnorm_api import RnormApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRnormApi(unittest.TestCase):
    """RnormApi unit test stubs"""

    def setUp(self):
        self.api = api.rnorm_api.RnormApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_calcrnorm(self):
        """Test case for calcrnorm

        generates n obs from a normal distribution with mean m  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
