# coding: utf-8

"""
    ocputest

    simple test  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.myfun_get_api import MyfunGetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMyfunGetApi(unittest.TestCase):
    """MyfunGetApi unit test stubs"""

    def setUp(self):
        self.api = api.myfun_get_api.MyfunGetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_library_ecocpu_r_myfun_json_get(self):
        """Test case for library_ecocpu_r_myfun_json_get

        display myfun  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
