# coding: utf-8

"""
    ocoutest

    simple test  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.bostonprint_api import BostonprintApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBostonprintApi(unittest.TestCase):
    """BostonprintApi unit test stubs"""

    def setUp(self):
        self.api = api.bostonprint_api.BostonprintApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_library_mass_data_boston_print_get(self):
        """Test case for library_mass_data_boston_print_get

        Boston data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
