# coding: utf-8

"""
    ocputest

    simple test  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.myfun_post_api import MyfunPostApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMyfunPostApi(unittest.TestCase):
    """MyfunPostApi unit test stubs"""

    def setUp(self):
        self.api = api.myfun_post_api.MyfunPostApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_calcmyfun(self):
        """Test case for calcmyfun

        calc myfun using parameter x  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
