# coding: utf-8

# flake8: noqa

"""
    ecocat

    simple test  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.bostonprint_api import BostonprintApi
from swagger_client.api.myfun_get_api import MyfunGetApi
from swagger_client.api.myfun_post_api import MyfunPostApi
from swagger_client.api.rnorm_api import RnormApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.body import Body
from swagger_client.models.body1 import Body1
