# coding: utf-8

# flake8: noqa
"""
    ocputest

    simple test  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.body import Body
from swagger_client.models.body1 import Body1
